from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate

load_dotenv()

llm = HuggingFaceEndpoint(
    model="meta-llama/Llama-3.1-8B-Instruct",
    task="conversational",
    provider="featherless-ai"
)

model = ChatHuggingFace(llm=llm)


# First prompt: we want the LLM to generate a detailed report.
template1 = PromptTemplate(
    template="Write a detailed report on {topic}",
    input_variables=["topic"]
)

# Second prompt: this prompt will take the FIRST model's output as input.
template2 = PromptTemplate(
    # NOTE: use "\n", not "/n", for a new line.
    template="Write a 5 line summary on the following text.\n{text}",
    input_variables=["text"]
)


# Step 1: Fill {topic} with "black hole".
#
# PromptTemplate itself doesn't call the LLM.
# .invoke() only creates the actual prompt/message from the template.
prompt1 = template1.invoke(
    {"topic": "black hole"}
)


# Step 2: Send the generated prompt to the model.
#
# result1 is the model's response object (AIMessage).
result1 = model.invoke(prompt1)


# .content gives us the actual text generated by the model.
#
# So:
# result1          → complete AIMessage object
# result1.content  → only the generated text
#
# We take that text and put it into {text} of the second prompt.
prompt2 = template2.invoke(
    {"text": result1.content}
)


# Step 3: Send the second prompt to the model.
# The model now summarizes the report generated in Step 2.
result2 = model.invoke(prompt2)


# Again, .content extracts only the actual text from the AIMessage.
print(result2.content)


# COMPLETE THINKING:
#
# "black hole"
#      ↓
# template1.invoke()
#      ↓
# prompt1
#      ↓
# model.invoke()
#      ↓
# result1 (AIMessage)
#      ↓
# result1.content  ← extract generated text
#      ↓
# template2.invoke()
#      ↓
# prompt2
#      ↓
# model.invoke()
#      ↓
# result2
#      ↓
# result2.content
#
# IMPORTANT:
# Here we are manually passing result1.content into the second prompt.
# Later, Output Parsers will help us control/convert model outputs
# into more useful formats instead of manually handling raw responses.