from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate

# StructuredOutputParser lets us define the fields we want
# in the LLM's response.
from langchain_classic.output_parsers.structured import (
    StructuredOutputParser,
    ResponseSchema
)


load_dotenv()


llm = HuggingFaceEndpoint(
    model="meta-llama/Llama-3.1-8B-Instruct",
    task="conversational",
    provider="featherless-ai"
)

model = ChatHuggingFace(llm=llm)


# ResponseSchema defines the expected fields.
#
# Here we are telling the parser:
# "I want 3 fields: fact_1, fact_2 and fact_3."
schema = [
    ResponseSchema(
        name="fact_1",
        description="Fact 1 about the topic."
    ),
    ResponseSchema(
        name="fact_2",
        description="Fact 2 about the topic."
    ),
    ResponseSchema(
        name="fact_3",
        description="Fact 3 about the topic."
    ),
]


# Creates a StructuredOutputParser using our schema.
parser = StructuredOutputParser.from_response_schemas(schema)


template = PromptTemplate(
    template="""Give 3 facts about {topic}
{format_instructions}""",

    # IMPORTANT:
    # {topic} is also used in the template,
    # so it should be included here.
    input_variables=["topic"],

    # get_format_instructions() generates instructions
    # telling the LLM how the output should be formatted.
    partial_variables={
        "format_instructions": parser.get_format_instructions()
    }
)


# Fill {topic} and create the actual prompt.
prompt = template.invoke(
    {"topic": "Black Hole"}
)


# Send the prompt to the LLM.
result = model.invoke(prompt)


# result.content = raw text generated by the LLM.
#
# parser.parse() takes that text and converts it
# into the structured output defined by our schema.
output = parser.parse(result.content)


print(output)


# ============================================================
# MAIN LIMITATION OF StructuredOutputParser
# ============================================================
#
# StructuredOutputParser gives us a DEFINED FORMAT,
# but it does NOT provide strong data validation.
#
# For example, our schema says:
#
# fact_1
# fact_2
# fact_3
#
# But it does not strongly enforce things like:
#
# - fact_1 must be a string
# - fact_2 must be a string
# - fact_3 must be a string
# - a value must belong to a specific set
# - a number must actually be an integer
#
# It mainly helps the LLM follow the requested structure
# and then parses that structured response.
#
# So:
#
# StructuredOutputParser
#        ↓
# Defines expected fields
#        ↓
# Parses structured output
#        ↓
# ❌ Strong schema/type validation is not provided
#
#
# This is where PydanticOutputParser becomes useful.
#
# PydanticOutputParser
#        ↓
# Pydantic Model
#        ↓
# Defines fields + types + constraints
#        ↓
# Parses + validates the output
#
# Example:
#
# class Person(BaseModel):
#     name: str
#     age: int
#
# Now "age" is expected to actually be an integer.