from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate

# PydanticOutputParser converts the LLM's JSON output
# into a validated Pydantic object.
from langchain_core.output_parsers import PydanticOutputParser

# BaseModel → used to define our output schema.
# Field → lets us add descriptions and validation rules.
from pydantic import BaseModel, Field


load_dotenv()


llm = HuggingFaceEndpoint(
    model="meta-llama/Llama-3.1-8B-Instruct",
    task="conversational",
    provider="featherless-ai"
)

model = ChatHuggingFace(llm=llm)


# We define the EXACT structure we expect from the LLM.
#
# Expected output:
# {
#     "name": "...",
#     "age":  ...,
#     "city": "..."
# }
class Person(BaseModel):

    # Must be a string
    name: str = Field(
        description="Name of the person"
    )

    # Must be an integer AND greater than 18.
    #
    # gt=18 means:
    # age > 18
    age: int = Field(
        gt=18,
        description="Age of the person."
    )

    # Must be a string
    city: str = Field(
        description="Name of the city from where person belongs to"
    )


# Connect our Pydantic schema with LangChain's parser.
#
# Now the parser knows:
# - which fields should exist
# - what their types should be
# - what validation rules should be applied
parser = PydanticOutputParser(
    pydantic_object=Person
)


template = PromptTemplate(
    template="""Generate the name, age & city of a fictional {place} person.

Return ONLY the JSON object.
Do NOT write Python code.
Do NOT add any explanation.
Do NOT use markdown code fences.

{format_instructions}""",

    input_variables=["place"],

    # Automatically generates instructions for the LLM
    # based on the Person Pydantic model.
    partial_variables={
        "format_instructions": parser.get_format_instructions()
    }
)


# Fill {place} with "indian".
prompt = template.invoke(
    {"place": "indian"}
)


# Send the prompt to the LLM.
result = model.invoke(prompt)


# result.content = raw text generated by the LLM.
#
# parser.parse() does TWO important things:
#
# 1. Parses the JSON
# 2. Validates it against the Person model
#
# So if the model returns something like:
#
# {
#     "name": "Rahul",
#     "age": 25,
#     "city": "Delhi"
# }
#
# we get:
#
# Person(name="Rahul", age=25, city="Delhi")
#
# But if the model returns:
#
# "age": 16
#
# validation fails because we specified:
# age > 18
output = parser.parse(result.content)


print(output)


# print(prompt)
# Uncomment this if you want to see the actual prompt
# sent to the model, including the format instructions.


# ============================================================
# WHY PydanticOutputParser IS MORE POWERFUL
# ============================================================
#
# JsonOutputParser:
#     Mainly parses valid JSON.
#
# StructuredOutputParser:
#     Defines expected fields/structure.
#
# PydanticOutputParser:
#     Defines structure + types + validation rules.
#
# Example:
#
# age: int = Field(gt=18)
#
# means:
#
#     age must be an integer
#     AND
#     age must be greater than 18
#
# So the flow is:
#
# LLM
#   ↓
# JSON response
#   ↓
# PydanticOutputParser
#   ↓
# Parse + Validate
#   ↓
# Person object