from dotenv import load_dotenv

from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import PromptTemplate

# RunnableBranch → choose one chain based on a condition
# RunnableLambda  → convert a normal Python function into a Runnable
from langchain_core.runnables import RunnableParallel, RunnableBranch, RunnableLambda

from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint

# PydanticOutputParser → converts LLM JSON output into a validated Pydantic object
from langchain_core.output_parsers import PydanticOutputParser

# Pydantic is used to define the structure we expect from the LLM
from pydantic import BaseModel, Field

# Literal restricts a value to specific allowed strings
from typing import Literal


load_dotenv()


llm = HuggingFaceEndpoint(
    model="meta-llama/Llama-3.1-8B-Instruct",
    task="conversational",
    provider="featherless-ai",
)

model1 = ChatHuggingFace(llm=llm)


llm2 = HuggingFaceEndpoint(
    model="Qwen/Qwen2.5-7B-Instruct",
    task="conversational",
    provider="featherless-ai"
)

model2 = ChatHuggingFace(llm=llm2)


parser = StrOutputParser()


# NEW: Pydantic model
# Defines exactly what structure we want from the LLM.
class Feedback(BaseModel):
    sentiment: Literal["positive", "negative"] = Field(
        description="Give the sentiment of the feedback either positive or negative"
    )


# PydanticOutputParser tells LangChain:
# "Parse the LLM output according to the Feedback structure."
parser2 = PydanticOutputParser(pydantic_object=Feedback)


# Prompt for sentiment classification
prompt1 = PromptTemplate(
    template="""Classify the sentiment of the following feedback
{feedback}

Return ONLY a JSON object, Do NOT write Python code,
Do NOT provide explanations,
Do NOT use markdown,
Do NOT include anything before or after the JSON

{format_instruction}""",

    input_variables=["feedback"],

    # Injects the exact format instructions generated by PydanticOutputParser.
    partial_variables={
        "format_instruction": parser2.get_format_instructions()
    }
)


# Flow:
# feedback → prompt → model → PydanticOutputParser
#
# Output will be a Feedback object, e.g.
# Feedback(sentiment="positive")
classifier_chain = prompt1 | model1 | parser2


prompt2 = PromptTemplate(
    template="Write an appropriate response to this positive feedback \n {feedback}",
    input_variables=["feedback"]
)


prompt3 = PromptTemplate(
    template="Write an appropriate response to this negative feedback \n {feedback}",
    input_variables=["feedback"]
)


# NEW: RunnableBranch
#
# It works like if / elif / else:
#
# if sentiment == "positive":
#     run prompt2 chain
#
# elif sentiment == "negative":
#     run prompt3 chain
#
# else:
#     run default RunnableLambda
branch_chain = RunnableBranch(

    # Condition → chain
    (
        lambda x: x.sentiment == "positive",
        prompt2 | model2 | parser
    ),

    (
        lambda x: x.sentiment == "negative",
        prompt3 | model2 | parser
    ),

    # Default branch → used when no condition matches
    #
    # RunnableLambda converts this normal Python function
    # into a LangChain Runnable.
    RunnableLambda(lambda x: "Couldn't find sentiment")
)


# Complete workflow:
#
# feedback
#    ↓
# classifier_chain
#    ↓
# Feedback(sentiment="positive"/"negative")
#    ↓
# branch_chain
#    ↓
# appropriate response
chain = classifier_chain | branch_chain


print(
    chain.invoke(
        {"feedback": "this is a wonderful phone at this price range"}
    )
)